# Generated by Django 5.1.7 on 2025-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_rating',
            field=models.CharField(choices=[('All Ages', 'All Ages'), ('5+', '5+'), ('8+', '8+'), ('13+', '13+'), ('18+', '18+')], default='All Ages', max_length=20),
        ),
    ]
